FROM onnc-prebuilt-external

WORKDIR /home/user/onnc-prebuilt
RUN sudo chown user:user /home/user/onnc-prebuilt

# See .dockerignore
COPY --chown=user:user ./ ./

RUN ln -s ../onnc-prebuilt-external/onncroot

RUN MAX_MAKE_JOBS=8 \
    BUILD_EXTERNAL=false \
    ./build.sh dbg ; \
    echo $? > ci-build-result.txt
